/***********************************************************************
THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY
DEVELOPER: Zihan Chen(vczh)
***********************************************************************/
#include "Vlpp.h"

#include "..\..\Source\Regex\Regex.h"
#include "..\..\Source\Regex\Automaton\RegexData.h"
#include "..\..\Source\Regex\Automaton\RegexAutomaton.h"
#include "..\..\Source\Regex\AST\RegexExpression.h"
#include "..\..\Source\Regex\AST\RegexWriter.h"
#include "..\..\Source\Regex\RegexPure.h"
#include "..\..\Source\Regex\RegexRich.h"
