/***********************************************************************
THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY
DEVELOPER: Zihan Chen(vczh)
***********************************************************************/
#include "VlppRegex.h"

#include "..\..\Source\Regex\Regex.cpp"
#include "..\..\Source\Regex\RegexAutomaton.cpp"
#include "..\..\Source\Regex\RegexData.cpp"
#include "..\..\Source\Regex\RegexExpression.cpp"
#include "..\..\Source\Regex\RegexParser.cpp"
#include "..\..\Source\Regex\RegexPure.cpp"
#include "..\..\Source\Regex\RegexRich.cpp"
#include "..\..\Source\Regex\RegexWriter.cpp"
