/***********************************************************************
THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY
DEVELOPER: Zihan Chen(vczh)
***********************************************************************/
#include "VlppRegex.h"

#include "..\..\Source\Regex\Regex.cpp"
#include "..\..\Source\Regex\RegexPure.cpp"
#include "..\..\Source\Regex\RegexRich.cpp"
#include "..\..\Source\Regex\AST\RegexExpression.cpp"
#include "..\..\Source\Regex\AST\RegexExpression_CanTreatAsPure.cpp"
#include "..\..\Source\Regex\AST\RegexExpression_CharSet.cpp"
#include "..\..\Source\Regex\AST\RegexExpression_GenerateEpsilonNfa.cpp"
#include "..\..\Source\Regex\AST\RegexExpression_HasNoExtension.cpp"
#include "..\..\Source\Regex\AST\RegexExpression_IsEqual.cpp"
#include "..\..\Source\Regex\AST\RegexParser.cpp"
#include "..\..\Source\Regex\AST\RegexWriter.cpp"
#include "..\..\Source\Regex\Automaton\RegexAutomaton.cpp"
